[package]
name = "mipsmatch"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
elf = "0.7.4"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_with = "3.12.0"
serde-hex = "0.1.0"
