name: Format

on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
